---
# tasks file for helloworld

- name: Copying the application file
  copy:
    src: helloworld.js
    dest: /home/ec2-user/
    owner: ec2-user
    group: ec2-user
    mode: 0644

- name: Copying the upstart file
  copy:
    src: helloworld.service
    dest: /lib/systemd/system/helloworld.service
    owner: root
    group: root
    mode: 0644

- name: Starting the HelloWorld node service
  become: yes
  become_user: root
  service:
    name: helloworld
    state: started
